language: go
sudo: false
notifications:
  email: false
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
go:
  - 1.11.x
  - 1.12.x
  - master
matrix:
  fast_finish: true
  allow_failures:
    - go: master
env:
  global:
    - GO111MODULE=on
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
before_install:
  - go mod download
install: go build ./...
script: go test -race -v -coverprofile=profile.cov $(go list ./...)
after_script:
  - go get github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
